import { useState } from "react";
import { api } from "./api/client";
import { settings } from "./store/settings";

// The sign-in gate. Shown when the backend reports auth is required and this browser has no
// valid session cookie yet. The token is generated by the backend and printed at startup (and
// stored in the project dir); the user pastes it once, the backend sets a 30-day cookie.
export function Login({ onAuthed }: { onAuthed: () => void }) {
  const [token, setToken] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const brand = settings.get().portalName || "Hermes";

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!token.trim() || busy) return;
    setBusy(true);
    setError(null);
    try {
      await api.login(token.trim());
      onAuthed();
    } catch {
      setError("That access token was not accepted. Check the token printed by the portal at startup.");
      setBusy(false);
    }
  };

  return (
    <div className="login-screen">
      <form className="login-card" onSubmit={submit}>
        <div className="brand login-brand">
          <span className="dot" />
          <span className="display brand-name">{brand}</span>
          <span className="mono brand-sub">Mission Control</span>
        </div>
        <p className="login-hint">
          This portal is protected. Paste the access token printed in the server log
          (or found in <code className="mono">~/.hermes-mc/portal-settings.json</code>) to sign in.
        </p>
        <input
          className="login-input mono"
          type="password"
          autoFocus
          placeholder="access token"
          value={token}
          onChange={(e) => setToken(e.target.value)}
        />
        {error && <div className="login-error">{error}</div>}
        <button className="login-btn" type="submit" disabled={busy || !token.trim()}>
          {busy ? "Signing in…" : "Sign in"}
        </button>
      </form>
    </div>
  );
}
